name = "Dataiku"
uuid = "9323d230-fd34-11e8-0857-0f91225e0c0f"
authors = ["CÃ©lian Haydont <celian.haydont@dataiku.com>"]
version = "0.1.0"

[deps]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
BufferedStreams = "e1450e63-4bb3-523b-b2a4-4ffa8c0fd77d"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
CSV = "0.5"
DataFrames = "^0.18"
HTTP = "^0.8"
JSON = "^0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
